site_name: UrbanWorm
theme:
  name: material
  custom_dir: overrides
  icon:
    logo: urabn_worm_logo
    repo: fontawesome/brands/github
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: light blue
      accent: green

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: purple
      accent: green

plugins:
  - search
  - mkdocstrings:
      default_handler: python
  - autorefs
  - git-revision-date
  - mkdocs-jupyter:
      include_source: True
      execute: False

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true

copyright: Copyright &copy; 2025 Xiaohao Yang